# Generated by Django 3.0.4 on 2020-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_auto_20200331_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='default.jpg', height_field=200, upload_to='media/profile_pics', width_field=200),
        ),
    ]
